AY2425S1-CS2113-T10-3/tp

- src/main/java/author/Author.java
- src/main/java/author/AuthorList.java
- src/main/java/commands/DeleteAuthorCommand.java
- src/main/java/commands/DeleteMangaCommand.java
- src/main/java/constants/Command.java
- src/main/java/manga/Manga.java
- src/main/java/parser/Parser.java
> Implement delete functionality for manga and author

- src/main/java/constants/Options.java
- src/main/java/constants/Regex.java
- src/main/java/parser/Parser.java
- text-ui-test/EXPECTED.TXT
- text-ui-test/input.txt
Branch to ensure that [MangaTantou only takes in input arguments enclosed in double quotes](https://github.com/AY2425S1-CS2113-T10-3/tp/issues/12)
> Branch fix input command format

- src/main/java/author/Author.java
- src/main/java/author/AuthorList.java
- src/main/java/commands/ViewMangasCommand.java
- src/main/java/manga/MangaList.java
- src/main/java/parser/Parser.java
- src/test/java/author/AuthorListTest.java
- src/test/java/author/AuthorTest.java
- src/test/java/manga/MangaListTest.java
- src/test/java/parser/ParserTest.java
Fixes #16. 
~~JUnit tests to be added~~
Update: JUnit tests added.
> Implement view mangas command

- src/main/java/author/Author.java
- src/main/java/commands/AddDeadlineCommand.java
- src/main/java/commands/DeleteDeadlineCommand.java
- src/main/java/constants/Command.java
- src/main/java/constants/Options.java
- src/main/java/manga/Manga.java
- src/main/java/manga/MangaList.java
- src/main/java/parser/Parser.java
- src/test/java/author/AuthorTest.java
- src/test/java/commands/AddDeadlineCommandTest.java
- src/test/java/commands/DeleteDeadlineCommandTest.java
- src/test/java/manga/MangaListTest.java
Note that the option to add a deadline date is "-b" or "-by". I changed the command to delete a deadline to deleteDeadline since the originally proposed method, using deadline -d, caused conflicts.
> Added functionality to add, view, and delete deadlines

- src/main/java/commands/DeleteAuthorCommand.java
- src/test/java/commands/DeleteAuthorCommandTest.java
- src/test/java/commands/DeleteMangaCommandTest.java
- text-ui-test/EXPECTED.TXT
Previous JUnit tests for these functions did not invoke the deleteManga and deleteAuthor commands correctly. This PR seeks to amend issue #20.
> Amendments to JUnit Tests for deleteManga and deleteAuthor

- src/main/java/commands/DeleteAuthorCommand.java
- src/main/java/commands/DeleteMangaCommand.java
> Add assertions and logs for deleteManga and deleteAuthor

- build.gradle
- src/main/java/commands/AddAuthorCommand.java
- src/main/java/commands/AddMangaCommand.java
- src/main/java/commands/Command.java
- src/main/java/commands/DeleteAuthorCommand.java
- src/main/java/commands/DeleteMangaCommand.java
- src/main/java/parser/Parser.java
> Branch assertion and logging add manga command

- build.gradle
- src/main/java/commands/AddAuthorCommand.java
- src/main/java/commands/Command.java
- src/main/java/commands/DeleteAuthorCommand.java
- src/main/java/commands/DeleteMangaCommand.java
- src/main/java/parser/Parser.java
> Branch assertion and logging add author command

- src/main/java/author/AuthorList.java
- src/main/java/commands/ViewAuthorsCommand.java
- src/main/java/commands/ViewMangasCommand.java
>  Add Assertions and Logging for View commands

- .gitignore
- build.gradle
- src/main/java/Main.java
- src/main/java/author/Author.java
- src/main/java/author/AuthorList.java
- src/main/java/commands/AddAuthorCommand.java
- src/main/java/commands/AddDeadlineCommand.java
- src/main/java/commands/AddMangaCommand.java
- src/main/java/commands/ByeCommand.java
- src/main/java/commands/DeleteAuthorCommand.java
- src/main/java/commands/DeleteDeadlineCommand.java
- src/main/java/commands/DeleteMangaCommand.java
- src/main/java/manga/Manga.java
- src/main/java/manga/MangaList.java
- src/main/java/storage/Storage.java
- src/main/java/tantou/Tantou.java
- src/test/java/author/AuthorListTest.java
- src/test/java/author/AuthorTest.java
- src/test/java/commands/DeleteAuthorCommandTest.java
- src/test/java/commands/DeleteMangaCommandTest.java
- src/test/java/storage/StorageTest.java
- src/test/resources/testCatalog.json
Uses [Gson 2.11.0](https://github.com/google/gson) with Apache License 2.0 [https://www.apache.org/licenses/LICENSE-2.0](https://www.apache.org/licenses/LICENSE-2.0) as approved in [issue #27](https://github.com/nus-cs2113-AY2425S1/forum/issues/27) from upstream.
> Implement Storage for data saving

- src/main/java/commands/DeleteAuthorCommand.java
- src/main/java/commands/DeleteMangaCommand.java
- src/main/java/parser/Parser.java
- src/test/java/commands/DeleteAuthorCommandTest.java
- src/test/java/commands/DeleteMangaCommandTest.java
> Update author tagging and JavaDoc comments

- src/main/java/exceptions/InvalidCatalogCommandException.java
- src/main/java/exceptions/InvalidDeleteCommandException.java
- src/main/java/exceptions/MangaArgsWrongOrderException.java
- src/main/java/exceptions/NoAuthorProvidedException.java
- src/main/java/exceptions/NoMangaProvidedException.java
- src/main/java/parser/Parser.java
- src/test/java/parser/ParserTest.java
Fixes #66 
- Implemented additional tests to check for `Parser`'s defensiveness against potential poorly formatted inputs from the user
- Introduced custom exceptions to facilitate error identification
- Refactored checking methods like `hasAuthorFlagAndArgument` for better reusability for other commands (`view`, `schedule` and `sales`)
> Branch update parser tests

- src/main/java/commands/AddAuthorCommand.java
- src/main/java/commands/AddMangaCommand.java
- src/main/java/commands/AddSalesCommand.java
- src/main/java/commands/ByeCommand.java
- src/main/java/commands/DeleteAuthorCommand.java
- src/main/java/commands/DeleteMangaCommand.java
- src/main/java/storage/StorageHelper.java
Simplifies calls to save `authorList` to data file.
> Create utility class StorageHelper

- src/main/java/author/Author.java
- src/main/java/author/AuthorList.java
- src/main/java/commands/ViewAuthorsCommand.java
- src/main/java/commands/ViewMangasCommand.java
- src/main/java/constants/Regex.java
- src/main/java/manga/MangaList.java
- src/main/java/parser/Parser.java
- src/main/java/ui/PrintColumn.java
- src/main/java/ui/Ui.java
- src/test/java/author/AuthorListTest.java
- src/test/java/author/AuthorTest.java
- src/test/java/manga/MangaListTest.java
- text-ui-test/EXPECTED.TXT
> Branch view details

- src/main/java/author/AuthorList.java
- src/main/java/commands/AddAuthorCommand.java
- src/main/java/commands/AddMangaCommand.java
- src/main/java/commands/AddSalesCommand.java
- src/main/java/commands/DeleteAuthorCommand.java
- src/main/java/commands/ViewAuthorsCommand.java
- src/main/java/commands/ViewMangasCommand.java
- src/main/java/constants/Options.java
- src/main/java/constants/PrintFormat.java
- src/main/java/constants/Regex.java
- src/main/java/exceptions/AuthorNameTooLongException.java
- src/main/java/exceptions/InvalidViewCommandException.java
- src/main/java/exceptions/MangaNameTooLongException.java
- src/main/java/manga/MangaList.java
- src/main/java/parser/Parser.java
- src/main/java/ui/PrintColumn.java
- src/main/java/ui/Ui.java
- src/test/java/commands/AddAuthorCommandTest.java
- src/test/java/commands/AddMangaCommandTest.java
- text-ui-test/EXPECTED.TXT
> Update view command parser and add JavaDoc

- src/main/java/commands/ViewAuthorsCommand.java
- src/main/java/commands/ViewMangasCommand.java
- src/main/java/exceptions/AuthorDoesNotExistException.java
- src/main/java/exceptions/AuthorListEmptyException.java
- src/main/java/exceptions/MangaListEmptyException.java
- src/test/java/commands/ViewAuthorsCommandTest.java
- src/test/java/commands/ViewMangasCommandTest.java
- src/test/resources/testCatalog.json
> Add JUnit tests for view commands

- src/main/java/commands/AddAuthorCommand.java
- src/main/java/commands/AddMangaCommand.java
- src/main/java/commands/ByeCommand.java
- src/main/java/commands/Command.java
- src/main/java/commands/DeleteAuthorCommand.java
- src/main/java/commands/DeleteMangaCommand.java
- src/main/java/commands/GreetCommand.java
- src/main/java/parser/ArgumentFinder.java
- src/main/java/parser/ArgumentResult.java
- src/main/java/parser/AuthorArgumentFinder.java
- src/main/java/parser/MangaArgumentFinder.java
- src/main/java/parser/Parser.java
- src/main/java/tantou/Tantou.java
- src/test/java/commands/AddAuthorCommandTest.java
- src/test/java/commands/AddMangaCommandTest.java
- src/test/java/commands/DeleteAuthorCommandTest.java
- src/test/java/commands/DeleteMangaCommandTest.java
- src/test/java/parser/ParserTest.java
> Branch remove redundant parser checks

- .gitignore
- src/main/java/Main.java
- src/main/java/commands/AddAuthorCommand.java
- src/main/java/commands/AddDeadlineCommand.java
- src/main/java/commands/AddMangaCommand.java
- src/main/java/commands/AddSalesCommand.java
- src/main/java/commands/Command.java
- src/main/java/commands/DeleteAuthorCommand.java
- src/main/java/commands/DeleteMangaCommand.java
- src/main/java/commands/ViewAuthorsCommand.java
- src/main/java/commands/ViewMangasCommand.java
- src/main/java/storage/Storage.java
- src/main/java/tantou/Tantou.java
Fixes #120 
Log file is located in logs/tantou.log. Made a custom log message format. Also added the logs directory to .gitignore.
> Change log message output to a file

- docs/DeveloperGuide.md
- docs/UserGuide.md
> Branch fix docs

- docs/DeveloperGuide.md
> Update link to Command Inheritance file

- src/main/java/commands/ViewMangasCommand.java
> Remove redundant sout message in ViewMangasCommand

- .gitignore
- docs/UserGuide.md
- src/main/java/storage/Storage.java
- src/main/java/tantou/Tantou.java
> Make data and log files save to path relative to jar file

- docs/AboutUs.md
- docs/UserGuide.md
- docs/team/sarahchow03.md
> Sarah's PPP

- src/main/java/commands/AddSalesCommand.java
- src/main/java/exceptions/NumberLessThanZeroException.java
- src/main/java/exceptions/PriceWrongFormatException.java
- src/main/java/exceptions/QuantityWrongFormatException.java
- src/test/java/commands/AddSalesCommandTest.java
> Fix command exception messages

- src/main/java/commands/AddSalesCommand.java
- src/main/java/constants/Options.java
- src/main/java/exceptions/PriceTooLargeException.java
- src/main/java/exceptions/QuantityTooLargeException.java
- src/main/java/storage/AuthorDeserializer.java
- src/main/java/storage/AuthorListDeserializer.java
- src/main/java/storage/MangaDeserializer.java
- src/main/java/storage/MangaListDeserializer.java
- src/main/java/storage/Storage.java
- src/test/java/storage/AuthorDeserializerTest.java
- src/test/java/storage/MangaDeserializerTest.java
> Fix manual data

- docs/AboutUs.md
- docs/DeveloperGuide.md
- docs/UserGuide.md
- src/main/java/commands/AddSalesCommand.java
- src/main/java/storage/SaleDeserializer.java
- Fix link in AboutUs.md
- Fix bugs
> Final fixes

- docs/DeveloperGuide.md
The previous one did not work.
> Try another horizontal line in DG
